### PR TITLE
Fixed analytics bombardment on update action

### LINKED ISSUE #906: Change analytics on update action to sync action
- Analytics data fields should remain the same

### PR DESCRIPTION
**Pull request by elsoazemelet**
Closes #906

### CODE REVIEW

File: src/renderer/runtime/operations.ts [hunk 1]
```diff
@@ -205,6 +218,9 @@ export async function updateAction(
     })
     .catch(handleError)
     .finally(() => {
+      if (!syncWithGrid) {
```
Comment (SukuWc) [inline src/renderer/runtime/operations.ts]: syncWithGrid parameter should call syncWithGrid instead of sendToGrid which already contains the analytics code. This guard clause and the following analytics track call are redundant, i think.
